version: '3'
services:
  backend:
    build: .
    ports:
      - 8080:3000
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: katakunci
  